config/routes.rb
Rails.application.routes.draw do

#管理者用deviseルート
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#会員用deviseルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  

#会員用
    root to: 'public/homes#top'

    get 'users' => 'public/users#show', as: 'user'
    get 'users/edit' => 'public/users#edit', as: 'user_edit'
    patch 'users' => 'public/users#update'
    get 'users/exit' => 'public/users#exit', as: 'user_exit'

    get 'subitems/new' => 'public/subitems#new', as: 'new_subitem'
    post 'subitems' => 'public/subitems#create', as: 'create_subitem'
    get 'subitems/:id' => 'public/subitems#show', as: 'subitem'
    get 'subitems' => 'public/subitems#index', as: 'subitems'
    get 'subitems/:id/edit' => 'public/subitems#edit', as: 'edit_subitem'
    patch 'subitems/:id' => 'public/subitems#update', as: 'update_subitem'
    delete 'subitems/:id' => 'public/subitems#destroy', as: 'destroy_subitem'
    post 'subitems/:id' => 'public/subitems#update_index', as: 'subitems_update'
    delete 'subitems' => 'public/subitems#destroy_all', as: 'all_destroy_subitem'

    get 'homes/top'
    get 'about' => 'public/homes#about', as: 'about'

    get 'shoppingmemos/index' => 'public/shoppingmemos#index'
    post 'shoppingmemos/index' => 'public/shoppingmemos#selected_create'
    post 'shoppingmemos/:id' => 'public/shoppingmemos#delete_memo', as: 'delete_shoppingmemo'
    get 'shoppingmemos/finish' => 'public/shoppingmemos#finish', as: 'shopping_finish'
    patch 'shoppingmemos/update_all', to: 'public/shoppingmemos#update_all'
    # sub_itemの一覧画面のソート
    get 'sub_item/index/sort_default', to: 'public/subitems#index', as: 'sort_default'
    get 'sub_item/index/sort_category', to: 'public/subitems#index', as: 'sort_category'
    get 'sub_item/index/sort_name', to: 'public/subitems#index', as: 'sort_name'

    get 'notification/index', to: 'public/notification#index', as: 'notifications'
    delete 'notification/:id', to: 'public/notification#destroy', as: 'notification_destroy'

#管理者用
  namespace :admin do
    resources :users
    resources :items
    resources :categories
  end
# ゲストログイン
  post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :sub_items
  belongs_to :category
  has_one_attached :item_image
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path, notice: "新規ものを作成しました"
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
    @colorCode = @item.category.color_code
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def confirm
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id), notice: "内容を更新しました"
    else
      render :edit,notice: "更新に失敗しました"
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to admin_items_path, notice: "ものを削除しました"
    else
      render :show, notice: "ものの削除に失敗しました"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :category_id, :preserve_method, :how_to_choose,
                                :limit, :item_image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">もの編集</h1>
  <div class="col-10-md">
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch, local: true do |f| %>
    <table class="table table-borderless">
      <tr>
        <th>
          ものの名前
        </th>
        <td>
          <%= f.text_field :name %>
        </td>
      </tr>
      <tr>
        <th>
          画像
        </th>
        <td>
          <%= f.file_field :item_image %>
        </td>
      </tr>
      <tr>
        <th>
          カテゴリ
        </th>
        <td>
          <%= f.collection_select(:category_id, Category.all, :id, :name) %>
          <!--★-->
          <!--カテゴリのボタンの色を変更する処理、余裕があったら記述する-->
          <!--<input type="hidden" id="colorCode" class="colorCode">-->
        </td>
      </tr>
      <tr>
        <th>
          保存方法
        </th>
        <td>
            <%= f.text_area :preserve_method, class: 'form_control', cols: "50" %>
        </td>
      </tr>
      <tr>
        <th>
          選び方
        </th>
        <td>
            <%= f.text_area :how_to_choose, class: 'form_control', cols: "50" %>
        </td>
      </tr>
      <tr>
        <th>
          使用期限（目安）
        </th>
        <td>
            <%= f.text_area :limit, class: 'form_control', cols: "50" %>
        </td>
      </tr>
    </table>
    <%= f.submit "変更を保存する", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">もの一覧</h1>

  <div class="col-10-md">
    <%= link_to "もの新規登録", new_admin_item_path ,class: "btn btn-primary"%>
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>ものID</th>
            <th></th>
            <th>なまえ</th>
            <th>画像</th>
            <th>カテゴリ</th>
            <th></th>
            </tr>
          </thead>
          <tbody>
          <tr>
          <% @items.each do |item| %>
          <td><%= item.id %></td>
          <td>
            <% if item.item_image.attached? %>
              <%= image_tag item.item_image, size: "80x50" %>
            <% else %>
              <%= image_tag 'no_image', size: "80x50" %>
            <% end %>
          </td>
          <td><%= item.name %></td>
          <td>
            <% if item.category %>
            <div class="Button" style="background-color: <%= item.category.color_code %>">
              <%= item.category.name %>
            </div>
            <% end %>
          </td>
          <td>
            <%= link_to "詳細へ", admin_item_path(item.id), class: "btn btn-success" %>
          </td>
          </tr>
          </tbody>
          <% end %>
        </table>
        <%= paginate @items, theme: 'bootstrap-5' %>
      </div>

  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">もの新規登録</h1>
  <div class="col-12-md">
    <%= form_with model: @item, url: admin_items_path, method: :post, local: true do |f| %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>ものの名前</th>
            <td>
              <%= f.text_field :name, :size => "30" %>
            </td>
          </tr>
          <tr>
            <th>画像選択</th>
            <td>
              <%= f.file_field :item_image, accept: 'image/*' %>
            </td>
          </tr>
          <tr>
            <th>カテゴリ</th>
            <td>
              <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: "選択してください") %>
            </td>
          </tr>
          <tr>
            <th>保存方法</th>
            <td>
              <%= f.text_area :preserve_method, :size => "30" %>
            </td>
          </tr>
          <tr>
            <th>選び方</th>
            <td>
              <%= f.text_area :how_to_choose, :size => "30" %>
            </td>
          </tr>
          <tr>
            <th>使用期限</th>
            <td>
              <%= f.text_area :limit, :size => "30" %>
            </td>
          </tr>
        </thead>
      </table>
      <%= f.submit "確認画面へ", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">もの詳細</h1>
  <div class="col-10-md">
    <table class="table table-borderless">
      <tr>
        <th>
          ものの名前
        </th>
        <td>
          <%= @item.name %>
        </td>
      </tr>
      <tr>
        <th>
          画像
        </th>
        <td>
          <!--画像の登録がなければ保存されたnoimageを表示する-->
          <% if @item.item_image.present? %>
            <%= image_tag @item.item_image, size: "200x200" %>
          <% else %>
            <%= image_tag 'no_image', size: "200x200" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>
          カテゴリ
        </th>
        <td>
          <div class="Button" style="background-color: <%= @colorCode %>">
            <%= @item.category.name %>
          </div>
          </div>
        </td>
      </tr>
      <tr>
        <th>
          保存方法
        </th>
        <td>
            <%= @item.preserve_method %>
        </td>
      </tr>
      <tr>
        <th>
          選び方
        </th>
        <td>
            <%= @item.how_to_choose %>
        </td>
      </tr>
      <tr>
        <th>
          使用期限（目安）
        </th>
        <td>
            <%= @item.limit %>
        </td>
      </tr>
    </table>
    <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
    <%= link_to "削除する", admin_item_path(@item.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
  </div>
</div>