config/routes.rb
Rails.application.routes.draw do

#管理者用deviseルート
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#会員用deviseルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  

#会員用
    root to: 'public/homes#top'

    get 'users' => 'public/users#show', as: 'user'
    get 'users/edit' => 'public/users#edit', as: 'user_edit'
    patch 'users' => 'public/users#update'
    get 'users/exit' => 'public/users#exit', as: 'user_exit'

    get 'subitems/new' => 'public/subitems#new', as: 'new_subitem'
    post 'subitems' => 'public/subitems#create', as: 'create_subitem'
    get 'subitems/:id' => 'public/subitems#show', as: 'subitem'
    get 'subitems' => 'public/subitems#index', as: 'subitems'
    get 'subitems/:id/edit' => 'public/subitems#edit', as: 'edit_subitem'
    patch 'subitems/:id' => 'public/subitems#update', as: 'update_subitem'
    delete 'subitems/:id' => 'public/subitems#destroy', as: 'destroy_subitem'
    post 'subitems/:id' => 'public/subitems#update_index', as: 'subitems_update'
    delete 'subitems' => 'public/subitems#destroy_all', as: 'all_destroy_subitem'

    get 'homes/top'
    get 'about' => 'public/homes#about', as: 'about'

    get 'shoppingmemos/index' => 'public/shoppingmemos#index'
    post 'shoppingmemos/index' => 'public/shoppingmemos#selected_create'
    post 'shoppingmemos/:id' => 'public/shoppingmemos#delete_memo', as: 'delete_shoppingmemo'
    get 'shoppingmemos/finish' => 'public/shoppingmemos#finish', as: 'shopping_finish'
    patch 'shoppingmemos/update_all', to: 'public/shoppingmemos#update_all'
    # sub_itemの一覧画面のソート
    get 'sub_item/index/sort_default', to: 'public/subitems#index', as: 'sort_default'
    get 'sub_item/index/sort_category', to: 'public/subitems#index', as: 'sort_category'
    get 'sub_item/index/sort_name', to: 'public/subitems#index', as: 'sort_name'

    get 'notification/index', to: 'public/notification#index', as: 'notifications'
    delete 'notification/:id', to: 'public/notification#destroy', as: 'notification_destroy'

#管理者用
  namespace :admin do
    resources :users
    resources :items
    resources :categories
  end
# ゲストログイン
  post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sub_items, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "会員情報を更新しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">会員情報の編集</h1>
    <div class="col-10-md">
      <%= form_with model: @user, url: admin_user_path(@user), method: :patch, local: true do |f| %>
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>ニックネーム</th>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th>ステータス</th>
            <td>
              <strong>
	        		  <%= f.radio_button :is_active, :true %>
	       		    <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
	       		    <%= f.radio_button :is_active, :false %>
	       		    <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
	        		</strong>
	        	</td>
	        </tr>
	       </table>
	       	<%= f.submit "変更を保存", class:"btn btn-success" %>
				<% end %>
	     </div>
	   </div>
	</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">会員一覧</h1>
  <div class="col-10-md">
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>会員ID</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
            <th></th>
            <th></th>
            </tr>
          </thead>
          <tbody>
          <tr>
          <% @users.each do |user| %>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_active == true %>
              <p class="text-success fw-bold">有効</p>
            <% else %>
              <p class="text-secondary fw-bold">退会</p>
            <% end %>
          </td>
          <td>
            <%= link_to "詳細", admin_user_path(user.id), class: "btn btn-success" %>
          </td>
          </tr>
          </tbody>
          <% end %>
        </table>
        <%= paginate @users, theme: 'bootstrap-5' %>
      </div>

  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h1 class="mt-3 text-center bg-secondary border border-secondary">会員詳細</h1>
    <div class="col-10-md">

      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th>会員ID</th>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <th>ニックネーム</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>ステータス</th>
            <td>
            <% if @user.is_active == true %>
              <p class="text-success fw-bold">有効</p>
            <% else %>
              <p class="text-secondary fw-bold">退会</p>
            <% end %>
            </td>
          </tr>
          </thead>
        </table>
        <div class="row">
	       		<div class="col-md-12 d-flex justify-content-center">
	       				<%= link_to "編集する", edit_admin_user_path(@user.id), class: 'btn btn-success' %>
	       		</div>
	       	</div>
      </div>
    </div>
</div>