config/routes.rb
Rails.application.routes.draw do

#管理者用deviseルート
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end

#会員用deviseルート
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  

#会員用
    root to: 'public/homes#top'

    get 'users' => 'public/users#show', as: 'user'
    get 'users/edit' => 'public/users#edit', as: 'user_edit'
    patch 'users' => 'public/users#update'
    get 'users/exit' => 'public/users#exit', as: 'user_exit'

    get 'subitems/new' => 'public/subitems#new', as: 'new_subitem'
    post 'subitems' => 'public/subitems#create', as: 'create_subitem'
    get 'subitems/:id' => 'public/subitems#show', as: 'subitem'
    get 'subitems' => 'public/subitems#index', as: 'subitems'
    get 'subitems/:id/edit' => 'public/subitems#edit', as: 'edit_subitem'
    patch 'subitems/:id' => 'public/subitems#update', as: 'update_subitem'
    delete 'subitems/:id' => 'public/subitems#destroy', as: 'destroy_subitem'
    post 'subitems/:id' => 'public/subitems#update_index', as: 'subitems_update'
    delete 'subitems' => 'public/subitems#destroy_all', as: 'all_destroy_subitem'

    get 'homes/top'
    get 'about' => 'public/homes#about', as: 'about'

    get 'shoppingmemos/index' => 'public/shoppingmemos#index'
    post 'shoppingmemos/index' => 'public/shoppingmemos#selected_create'
    post 'shoppingmemos/:id' => 'public/shoppingmemos#delete_memo', as: 'delete_shoppingmemo'
    get 'shoppingmemos/finish' => 'public/shoppingmemos#finish', as: 'shopping_finish'
    patch 'shoppingmemos/update_all', to: 'public/shoppingmemos#update_all'
    # sub_itemの一覧画面のソート
    get 'sub_item/index/sort_default', to: 'public/subitems#index', as: 'sort_default'
    get 'sub_item/index/sort_category', to: 'public/subitems#index', as: 'sort_category'
    get 'sub_item/index/sort_name', to: 'public/subitems#index', as: 'sort_name'

    get 'notification/index', to: 'public/notification#index', as: 'notifications'
    delete 'notification/:id', to: 'public/notification#destroy', as: 'notification_destroy'

#管理者用
  namespace :admin do
    resources :users
    resources :items
    resources :categories
  end
# ゲストログイン
  post '/homes/guest_sign_in', to: 'public/homes#guest_sign_in'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_categories_side_menu.html.erb
  <div class="border border-secondary">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th>
            <strong>
              カテゴリ検索
            </strong>
          </th>
        </tr>
        <% categories.each do |category| %>
        <tr>
          <td>
            <%= link_to category.name %><br>
        <% end %>
          </td>
        </tr>
      </tbody>
    </table>

  </div>

app/views/layouts/_genre_side_menu.html.erb
<div class="col-2-md">
  <div class="border border-secondary">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th>
            <strong>
              カテゴリ検索
            </strong>
          </th>
        </tr>
        <% categories.each do |category| %>
        <tr>
          <td>
            <%= link_to category.name %><br>
        <% end %>
          </td>
        </tr>
      </tbody>
    </table>

  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>まいくつ</title>
    <!--fontawesome-->
    <script src="https://kit.fontawesome.com/a69f599634.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--webpackerを使用する設定-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

<body>
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
         <!--まいくつロゴ-->
          <a class="navbar-brand" alt="まいくつロゴ" href="/">
            <%= image_tag asset_path("まいくつ（ロゴ）.png") %>
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="Navbar">
                  <!--  会員のログイン時に表示されるメニュー　-->
                <% if user_signed_in? %>
                <div class="col">
                  <div class="row">
                    <div class="col-md-3">
                      ようこそ、<br>
                      <%= current_user.name %>さん!
                    </div>
                    <div class="col-md-9">
                      <div class="btn-group px-2">
                        <ul class="navbar-nav me-auto mb-2 md-md-() list-unstyled">
                          <% if unchecked_notifications.any? %>
                            <i class="fa fa-circle" style="color: blue;"></i>
                          <% end %>
                          <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-3">
                            <%= link_to notifications_path, class: 'nav-link' do %>
                              <i class="far fa-bell fa-3x"></i><br>
                                通知
                            <% end %>
                          </li>
                          <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-3">
                            <%= link_to new_subitem_path, class: 'nav-link' do %>
                              <i class="fas fa-cube fa-3x"></i><br>
                              こもの登録
                            <% end %>
                          </li>
                          <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-3">
                            <%= link_to subitems_path, class: 'nav-link' do %>
                              <i class="fas fa-cubes fa-3x"></i><br>
                              こもの一覧
                            <% end %>
                          </li>
                          <li class="nav-item btn btn-outline-secondary rounded btn-sm">
                            <%= link_to shoppingmemos_index_path, class: 'nav-link' do %>
                              <i class="fas fa-clipboard fa-3x"></i><br>
                               買い物メモ
                             <% end %>
                          </li>
                          <li class="nav-item btn btn-outline-secondary rounded btn-sm ml-2">
                            <%= link_to destroy_user_session_path, method: :DELETE, class: 'nav-link' do %>
                              <i class="fas fa-sign-out-alt fa-3x"></i><br>
                              ログアウト
                            <% end %>
                          </li>
                        </ul>
                      </div>
                  </div>
                </div>
              </div>
            <% elsif admin_signed_in? %>
            <!--　管理者のログイン時に表示されるメニュー　-->
            <div class="col">
              <div class="row">
                <div class="col-12">
                  <div class="btn-group px-2.5">
                    <ul class="navbar list-unstyled">
                      <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-2">
                        <%= link_to admin_items_path, class: 'nav-link' do %>
                          <i class="fas fa-cubes fa-3x"></i><br>
                          もの一覧
                        <% end %>
                      </li>
                      <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-2">
                        <%= link_to admin_categories_path, class: 'nav-link' do %>
                          <i class="far fa-folder fa-3x"></i><br>
                          カテゴリ一覧
                        <% end %>
                      </li>
                      <li class="nav-item btn btn-outline-secondary rounded btn-sm mr-2">
                        <%= link_to admin_users_path, class: 'nav-link' do %>
                        <i class="fas fa-users fa-3x"></i><br>
                          会員一覧
                        <% end %>
                      </li>
                      <li class="nav-item btn btn-outline-secondary rounded btn-sm">
                        <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link' do %>
                          <i class="fas fa-sign-out-alt fa-3x"></i><br>
                          ログアウト
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
        <% else %>
          <!--  管理者と会員共通非ログイン時表示メニュー -->
          <div class="col">
            <div class="row">
              <div class="col-12">
                <div class="btn-group px-2.5">
                  <ul class="navbar list-unstyled">
                    <li class="nav-item btn btn-outline-dark rounded btn-sm mr-4">
                      <%= link_to about_path, class: 'nav-link' do %>
                      <i class="far fa-hand-point-up fa-3x"></i><br>
                      ”まいくつ”とは？
                      <% end %><!--Aboutページ-->
                    </li>
                    <li class="nav-item btn btn-outline-dark rounded btn-sm mr-4">
                      <%= link_to new_user_registration_path, class: 'nav-link' do %>
                      <i class="fas fa-user fa-3x"></i><br>
                      新規登録
                      <% end %><!--会員用の新規登録ページへ--->
                    </li>
                    <li class="nav-item btn btn-outline-dark rounded btn-sm">
                      <%= link_to new_user_session_path, class: 'nav-link' do %>
                      <i class="fas fa-sign-in-alt fa-3x"></i><br>
                      ログイン
                      <% end %><!--会員のログインページ-->
                    </li>
                  </ul>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% notice %>
    <main class="mb-auto">
      <%= yield %>
    </main>

  </body>
</html>